#!/usr/bin/env node

/**
 * Interactive Setup Script for ResQdrant Backend
 * This helps you configure your .env file step by step
 */

const readline = require('readline');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

console.log('');
console.log('🚨 ResQdrant Backend - Interactive Setup');
console.log('==========================================');
console.log('');
console.log('This script will help you configure your backend/.env file.');
console.log('');

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, (answer) => {
      resolve(answer);
    });
  });
}

async function main() {
  console.log('Step 1: MongoDB Atlas Connection');
  console.log('----------------------------------');
  console.log('');
  console.log('You need:');
  console.log('1. Your MongoDB Atlas username (e.g., vishal_db_user)');
  console.log('2. Your MongoDB Atlas password');
  console.log('3. Your cluster URL (e.g., resqdrant.nkiljhx.mongodb.net)');
  console.log('4. Your database name (e.g., resqdrant)');
  console.log('');
  console.log('💡 To get these:');
  console.log('   1. Go to: https://cloud.mongodb.com/');
  console.log('   2. Database Access → Your user → Edit → Copy password');
  console.log('   3. Database → Connect → Connection string');
  console.log('');

  const hasInfo = await question('Do you have your MongoDB connection info ready? (yes/no): ');
  
  if (hasInfo.toLowerCase() !== 'yes' && hasInfo.toLowerCase() !== 'y') {
    console.log('');
    console.log('❌ Please get your MongoDB Atlas credentials first:');
    console.log('   1. Go to: https://cloud.mongodb.com/');
    console.log('   2. Log in');
    console.log('   3. Database Access → Edit your user → Get password');
    console.log('   4. Run this script again: node setup-env.js');
    console.log('');
    rl.close();
    return;
  }

  console.log('');
  const username = await question('MongoDB username (default: vishal_db_user): ') || 'vishal_db_user';
  const password = await question('MongoDB password (paste it here): ');
  
  if (!password || password.trim() === '') {
    console.log('');
    console.log('❌ Password is required!');
    console.log('   Go to MongoDB Atlas and reset your password if needed.');
    console.log('');
    rl.close();
    return;
  }

  const cluster = await question('Cluster URL (default: resqdrant.nkiljhx.mongodb.net): ') || 'resqdrant.nkiljhx.mongodb.net';
  const database = await question('Database name (default: resqdrant): ') || 'resqdrant';

  // Build connection string
  const mongoUri = `mongodb+srv://${username}:${password}@${cluster}/${database}?retryWrites=true&w=majority`;

  console.log('');
  console.log('Step 2: OpenAI API Key (Optional)');
  console.log('----------------------------------');
  console.log('');
  console.log('OpenAI enables AI-assisted emergency classification.');
  console.log('Backend works fine WITHOUT it (uses keyword detection).');
  console.log('');
  const useAI = await question('Do you want to enable AI? (yes/no, default: no): ');
  
  let openaiKey = '';
  if (useAI.toLowerCase() === 'yes' || useAI.toLowerCase() === 'y') {
    console.log('');
    console.log('Get your key from: https://platform.openai.com/api-keys');
    openaiKey = await question('OpenAI API key (starts with sk-): ');
  }

  // Create .env content
  const envContent = `# MongoDB Atlas Connection (FREE TIER)
# Generated by setup script on ${new Date().toISOString()}
MONGO_URI=${mongoUri}

# Server Configuration
PORT=5000
NODE_ENV=development

# OpenAI API Key (OPTIONAL)
${openaiKey ? `OPENAI_API_KEY=${openaiKey}` : '# OPENAI_API_KEY='}
`;

  // Write to .env file
  const envPath = path.join(__dirname, '.env');
  fs.writeFileSync(envPath, envContent);

  console.log('');
  console.log('✅ Configuration saved to backend/.env');
  console.log('');
  console.log('📋 Your configuration:');
  console.log(`   MongoDB User: ${username}`);
  console.log(`   MongoDB Cluster: ${cluster}`);
  console.log(`   Database: ${database}`);
  console.log(`   AI Enabled: ${openaiKey ? 'Yes' : 'No'}`);
  console.log('');
  console.log('⚠️  IMPORTANT: Check IP Whitelist');
  console.log('   1. Go to: https://cloud.mongodb.com/');
  console.log('   2. Network Access → Add IP Address');
  console.log('   3. Use: 0.0.0.0/0 (for testing)');
  console.log('   4. Wait 1-2 minutes for changes to apply');
  console.log('');
  console.log('🚀 Next steps:');
  console.log('   1. npm run dev');
  console.log('   2. Open: http://localhost:5000/api/health');
  console.log('   3. Should see: "database": "connected"');
  console.log('');

  rl.close();
}

main().catch((error) => {
  console.error('Error:', error);
  rl.close();
  process.exit(1);
});
